media: i2c: adv748x: Provide slab.h headers for kzalloc/kfree
Certain combinations of kernel configuration fail to compile ADV748x
with errors on kzalloc and kfree:

drivers/media/i2c/adv748x/adv748x-core.c:693:10: error: implicit
declaration of function ‘kzalloc’
[-Werror=implicit-function-declaration]
  state = kzalloc(sizeof(struct adv748x_state), GFP_KERNEL);

Fix this by providing include/slab.h

Fixes: e261761c3662 ("media: i2c: adv748x: add adv748x driver")
Signed-off-by: Kieran Bingham <kieran.bingham+renesas@ideasonboard.com>